### ISSUE TITLE
TypeError: Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by sangramrajekakade** [ph4r05/python-whois#1]
Traceback (most recent call last):
  File "whois_demo.py", line 3, in <module>
    w = ph4whois.whois('webscraping.com')
  File "/home/panacea/demo/venv/lib/python3.5/site-packages/ph4whois/__init__.py", line 32, in whois
    domain = extract_domain(url)
  File "/home/panacea/demo/venv/lib/python3.5/site-packages/ph4whois/__init__.py", line 88, in extract_domain
    domain = '.' + domain
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by dcale** [comment]
same issue... With python3
